name: Docker image for 15.0

on:
  workflow_dispatch:
    
permissions:
  packages: write
    
jobs:
  base:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Check out to doodba source
        uses: actions/checkout@v2
        with:
          repository: Tecnativa/doodba
          path: src
    
      - name: Move custom dockerfiles to src
        run: mv *.Dockerfile src/

      - name: Patch pip installer to allow caching
        run: |
          sed -i -E 's/^    _install_command = \["pip", "install", "--no-cache-dir", "-r"\]$/    _install_command = \["pip", "install", "-r"\]/' src/lib/doodbalib/installer.py
    
      - name: Get date & commit sha
        run: |
          echo "BUILD_DATE=$(date --rfc-3339 ns)" >> $GITHUB_OUTPUT && \
          echo "VCS_REF=$(git -C src rev-parse HEAD)" >> $GITHUB_OUTPUT
        id: build_args

      - name: Build base
        id: build_image_base
        uses: redhat-actions/buildah-build@v2
        with:
          image: doodba
          tags: 15.0-bookworm
          build-args: |
            ODOO_VERSION=15.0
            VCS_REF=${{ steps.build_args.outputs.VCS_REF }}
            BUILD_DATE=${{ steps.build_args.outputs.BUILD_DATE }}
          containerfiles: |
            src/base.Dockerfile
          context: ./src

      - name: Push base to GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image_base.outputs.image }}
          tags: ${{ steps.build_image_base.outputs.tags }}
          registry: ghcr.io/cmwedding-it
          username: oskardotglobal
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build onbuild
        id: build_image_onbuild
        uses: redhat-actions/buildah-build@v2
        with:
          image: doodba
          tags: 15.0-bookworm-onbuild
          build-args: |
            ODOO_VERSION=15.0
            VCS_REF=${{ steps.build_args.outputs.VCS_REF }}
            BUILD_DATE=${{ steps.build_args.outputs.BUILD_DATE }}
          containerfiles: |
            src/onbuild.Dockerfile
          extra-args: |
            --target onbuild
          context: ./src

      - name: Push onbuild to GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image_onbuild.outputs.image }}
          tags: ${{ steps.build_image_onbuild.outputs.tags }}
          registry: ghcr.io/cmwedding-it
          username: oskardotglobal
          password: ${{ secrets.GITHUB_TOKEN }}
    